---
apiVersion: v1
kind: Service
metadata:
  name: maintainerr
spec:
  type: NodePort
  selector:
    app: maintainerr
  ports:
    - name: http
      port: 6246
      protocol: TCP
      targetPort: 6246  
  externalIPs:
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222 
    - 192.168.0.223
    - 192.168.0.224
