---
apiVersion: v1
kind: Service
metadata:
  name: maintainerr
spec:
  type: NodePort
  selector:
    app: maintainerr
  ports:
    - name: http
      port: 6246
      protocol: TCP
      targetPort: 6246
      nodePort: 30646
