---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintainerr
  labels:
    app: maintainerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintainerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: maintainerr
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-worker-01
      imagePullSecrets:
      - name: image-registry-credentials
      containers:
      - name: maintainerr
        imagePullPolicy: IfNotPresent
        image: 192.168.50.222:32050/maintainerr/maintainerr@sha256:8251a1f0ba5d71acc878846a727fba566ec87cbfbf6a914fb881a5953af53d46
        ports:
        - name: http
          containerPort: 6246 
          protocol: TCP
        startupProbe:
          httpGet:
            path: /api/health/live
            port: http
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health/live
            port: http
          periodSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi
        env:
        - name: TZ
          value: "America/Denver"
        - name: user
          value: "1000"
        volumeMounts:
        - name: k8s-pv02
          mountPath: /config
          subPath: maintainerr/config
        - name: k8s-pv02
          mountPath: /opt/data
          subPath: maintainerr/opt/data
      volumes:
      - name: k8s-pv02
        persistentVolumeClaim:
          claimName: synology-k8s-pv02
